#!/usr/bin/env bash

# Post requests to https://faaast.download to get packaged files from the cli
# Example: faaast "npm install react"
# See the FAQs: https://faaast.download/faqs.php
COMMAND=$1

if [[ -z "$1" ]];
    then
    echo -e "Command not set";
    echo -e "You must include the command within quotes!";
    echo -e "Example: faaast \"npm install react\"";
    exit;
fi

ID=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 20 | head -n 1)
URL="https://faaast.download/faaast.php?cmd=${COMMAND// /+}&id=${ID}&api=1"
ERROR_URL="https://faaast.download/faaast.php?cmd=${COMMAND// /+}&id=${ID}&error=true"

echo -e "Posting to ${URL}";
echo -e "";

FILE=$(curl -s "$URL" | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["'file'"]';)

if [[ "$FILE" != "An error occured" ]];
    then
        wget "$FILE";
    else
        echo -e "An error occured.";
        echo -e "See more at ${ERROR_URL}";
fi
